import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { createDatabase } from '../database.mjs';
import { createHandler } from '../handler.mjs';
import { seedAdmin } from '../auth.mjs';

test('authenticated OPD workflow, patient reuse, invoice linking, and billing regressions', async t => {
  const db = await createDatabase({connectionString:'',dataDir:'memory://'});
  await seedAdmin(db,'test','test-password-only');
  const server = http.createServer(createHandler(db));
  await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
  t.after(async () => { await new Promise(resolve=>server.close(resolve)); await db.close(); });
  const base = `http://127.0.0.1:${server.address().port}`;
  let cookie = '';
  async function request(path,method='GET',body) {
    const r = await fetch(base+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});
    return {status:r.status,value:await r.json(),cookie:r.headers.get('set-cookie')};
  }
  assert.equal((await request('/api/doctors')).status,401);
  const login = await request('/api/login','POST',{username:'test',password:'test-password-only'});
  assert.equal(login.status,200); cookie = login.cookie.split(';')[0];
  const doctors = (await request('/api/doctors')).value;
  assert.equal(doctors.length,3);
  const patient = (await request('/api/patients','POST',{name:'Test Patient',mobile:'9876543210',age:'40',gender:'Female',address:'Test address'})).value;
  assert.match(patient.patient_uid,/^YPC-UID-\d{6}$/);
  const duplicate = await request('/api/patients','POST',{name:'Test Patient',mobile:'9876543210'});
  assert.equal(duplicate.status,409); assert.equal(duplicate.value.matches[0].id,patient.id);
  const input = {patient_id:patient.id,doctor_id:doctors[0].id,illness_code:'piles',consultation_fee_paise:50000,payment_status:'paid',payment_mode:'CASH'};
  assert.equal((await request('/api/opd-visits','POST',{...input,doctor_id:'11111111-1111-4111-8111-111111111111'})).status,400);
  const first = await request('/api/opd-visits','POST',input);
  assert.equal(first.status,201);
  const visit = first.value;
  const second = (await request('/api/opd-visits','POST',{...input,illness_code:'other',custom_illness:'Follow-up concern',payment_status:'unpaid'})).value;
  assert.notEqual(second.opd_number,visit.opd_number); assert.equal(second.patient_uid,visit.patient_uid);
  assert.equal((await request('/api/opd-visits?q=9876543210')).value.length,2);
  assert.equal((await request('/api/opd-visits?q=Follow-up')).value.length,1);
  assert.equal((await request('/api/invoices')).value.length,0,'saving OPD never issues an invoice');
  const linked = await Promise.all([request(`/api/opd-visits/${visit.id}/invoice`,'POST',{}),request(`/api/opd-visits/${visit.id}/invoice`,'POST',{})]);
  assert.deepEqual(linked.map(x=>x.status).sort(),[200,201]);
  assert.equal(linked[0].value.id,linked[1].value.id);
  const invoice = linked[0].value;
  assert.equal(invoice.registration,patient.patient_uid); assert.equal(invoice.received_paise,59000); assert.equal(invoice.total_paise,59000);
  assert.equal((await request(`/api/opd-visits/${visit.id}`)).value.invoice.id,invoice.id);
  const unpaid = (await request(`/api/opd-visits/${second.id}/invoice`,'POST',{})).value;
  assert.equal(unpaid.received_paise,0);
  const overpay = await Promise.all([request(`/api/invoices/${unpaid.id}/payments`,'POST',{amount_paise:40000,mode:'CASH'}),request(`/api/invoices/${unpaid.id}/payments`,'POST',{amount_paise:40000,mode:'CASH'})]);
  assert.deepEqual(overpay.map(x=>x.status).sort(),[201,400]);
  for (const status of ['paid','paid','unpaid','unpaid']) assert.equal((await request(`/api/invoices/${unpaid.id}/payment-status`,'POST',{status})).status,200);
  const reopened = (await request(`/api/invoices/${unpaid.id}`)).value;
  assert.equal(reopened.received_paise,0); assert.equal(reopened.payments.length,1); assert.equal(reopened.payment_adjustments.length,2);
  assert.equal((await request(`/api/invoices/${unpaid.id}/void`,'POST',{reason:'Test correction'})).status,200);
  assert.equal((await request(`/api/invoices/${unpaid.id}/payments`,'POST',{amount_paise:1,mode:'CASH'})).status,409);
  const extraVisit=(await request('/api/opd-visits','POST',input)).value;
  const extraInvoice=(await request(`/api/opd-visits/${extraVisit.id}/invoice`,'POST',{patient_name:'Tampered',paid_paise:999999,items:[{type:'Service',description:`Consultation - ${extraVisit.doctor_name}`,quantity:1,unit_price_paise:50000},{type:'Medicine',description:'Test medicine',quantity:1,unit_price_paise:10000}]})).value;
  assert.equal(extraInvoice.patient_name,'Test Patient');assert.equal(extraInvoice.total_paise,70800);assert.equal(extraInvoice.received_paise,59000);assert.equal(extraInvoice.balance_paise,11800);
  assert.equal((await request('/api/patients?q='+patient.patient_uid)).value[0].id,patient.id);
  const invoicesBefore=(await request('/api/invoices')).value.length;
  const badVisit=(await request('/api/opd-visits','POST',input)).value;
  assert.equal((await request(`/api/opd-visits/${badVisit.id}/invoice`,'POST',{items:[{type:'Service',description:'Tampered',quantity:1,unit_price_paise:1}]})).status,400);
  assert.equal((await request('/api/invoices')).value.length,invoicesBefore);
  await db.query('UPDATE doctors SET active=false WHERE id=$1',[doctors[0].id]);
  assert.equal((await request('/api/opd-visits','POST',input)).status,400);
  assert.equal((await request('/api/doctors')).value.length,2);
  assert.equal((await request(`/api/opd-visits/${visit.id}`)).value.doctor_name,doctors[0].name);
  for(const path of ['/api/opd-visits/invalid','/api/invoices/999999']) assert.equal((await request(path)).status,404);
  assert.equal((await fetch(base+'/api/opd-visits',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:'{invalid'})).status,400);
  assert.equal((await fetch(base+'/api/opd-visits',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,Origin:'https://unrelated.example'},body:'{}'})).status,403);
  await request('/api/logout','POST',{});
  assert.equal((await request('/api/opd-visits')).status,401);
});
