import { test, expect } from '@playwright/test';
import http from 'node:http';
import { createDatabase } from '../database.mjs';
import { seedAdmin } from '../auth.mjs';
import { createHandler } from '../handler.mjs';
let db,server,base;
test.beforeAll(async()=>{
  db=await createDatabase({connectionString:'',dataDir:'memory://'});await seedAdmin(db,'test','test-password-only');
  server=http.createServer(createHandler(db));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base=`http://127.0.0.1:${server.address().port}`;
});
test.afterAll(async()=>{if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}if(db)await db.close();});
test('OPD registration, returning patient, invoice prefill, save and print',async({page},testInfo)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);
  await page.getByLabel('Username').fill('test');await page.getByLabel('Password').fill('test-password-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();
  await expect(page.locator('#workspace')).toBeVisible();
  await page.getByRole('button',{name:'OPD',exact:true}).click();
  const form=page.locator('#opd-form');
  await expect(form.getByRole('combobox',{name:'Doctor',exact:true}).locator('option')).toHaveCount(4);
  await form.getByLabel('Patient name').fill('Browser Test Patient');
  await form.getByLabel('Mobile number').fill('9876501234');
  await form.getByLabel('Age',{exact:true}).fill('35');await form.getByRole('combobox',{name:'Gender',exact:true}).selectOption('Female');
  await form.getByLabel('Address',{exact:true}).fill('Test area, Lucknow');
  await form.getByRole('combobox',{name:'Doctor',exact:true}).selectOption({label:'Dr. Saurabh Mishra'});
  await form.getByRole('combobox',{name:'Illness',exact:true}).selectOption('other');await form.getByLabel('Other illness').fill('Test follow-up');
  await form.getByLabel('Consultation fee').fill('500');await form.getByRole('combobox',{name:'Payment status',exact:true}).selectOption('paid');
  await expect(form.getByRole('combobox',{name:'Payment mode',exact:true})).toBeVisible();await form.getByRole('combobox',{name:'Payment mode',exact:true}).selectOption('UPI');
  await expect(page.locator('#opd-total')).toContainText('590.00');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:testInfo.outputPath('opd-desktop.png'),fullPage:true});
  await page.getByRole('button',{name:'Save OPD registration',exact:true}).click();
  await expect(page.locator('#opd-detail')).toBeVisible();
  const uid=await page.locator('.uid-label').textContent();
  await expect(page.locator('#opd-detail')).toContainText('Test follow-up');
  await page.getByRole('button',{name:'OPD form / PDF',exact:true}).click();
  await expect(page.locator('#opd-print')).toBeVisible();
  await expect(page.locator('#opd-paper')).toContainText('OPD REGISTRATION');
  await expect(page.locator('#opd-paper')).toContainText('Munshipuliya, Lucknow, Uttar Pradesh');
  await expect(page.locator('#opd-paper')).toContainText('Dr. Saurabh Mishra');
  await expect(page.locator('#opd-paper')).toContainText('Test follow-up');
  await expect(page.locator('#opd-paper')).not.toContainText('Short note');
  expect(await page.locator('#opd-paper img').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
  await page.emulateMedia({media:'print'});
  await expect(page.locator('#opd-paper')).toBeVisible();await expect(page.locator('#detail')).toBeHidden();
  await expect(page.locator('#opd-detail')).toBeHidden();await expect(page.locator('.topbar')).toBeHidden();
  await page.pdf({path:testInfo.outputPath('opd-registration.pdf'),format:'A4',printBackground:true,displayHeaderFooter:false});
  await page.emulateMedia({media:'screen'});
  await page.getByRole('button',{name:'Back to OPD visit',exact:true}).click();
  await page.getByRole('button',{name:'Create invoice',exact:true}).click();
  await expect(page.locator('#invoice-opd-notice')).toBeVisible();
  await expect(page.locator('#invoice-form [name=patient_name]')).toHaveValue('Browser Test Patient');
  await expect(page.locator('#registration')).toHaveValue(uid);
  await expect(page.locator('#opd-invoice-payment')).toContainText('590.00');
  await expect(page.locator('.locked-charge .unit-price')).toBeDisabled();
  await page.getByRole('button',{name:'Save invoice',exact:true}).click();
  await expect(page.locator('#detail')).toBeVisible();await expect(page.locator('#invoice-paper')).toContainText('Browser Test Patient');
  await page.emulateMedia({media:'print'});await expect(page.locator('.workspace-navigation')).toBeHidden();await expect(page.locator('#opd-detail')).toBeHidden();
  await expect(page.locator('#invoice-controls')).toBeHidden();
  await page.screenshot({path:testInfo.outputPath('invoice-print.png'),fullPage:true});
  await page.pdf({path:testInfo.outputPath('opd-invoice.pdf'),format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});
  await page.getByRole('button',{name:'OPD',exact:true}).click();await page.getByRole('button',{name:'New OPD registration',exact:true}).click();
  await page.getByLabel('Find a returning patient').fill('9876501234');await page.locator('.patient-match').click();
  await expect(page.locator('#selected-patient')).toContainText(uid);
  await form.getByRole('combobox',{name:'Doctor',exact:true}).selectOption({label:'Dr. Aman Mishra'});await form.getByRole('combobox',{name:'Illness',exact:true}).selectOption('piles');
  await form.getByLabel('Consultation fee').fill('500');
  await page.getByRole('button',{name:'Save OPD registration',exact:true}).click();await expect(page.locator('#opd-detail')).toBeVisible();
  await expect(page.locator('.uid-label')).toHaveText(uid);
  await page.getByRole('button',{name:'Create invoice',exact:true}).click();await page.getByRole('button',{name:'Save invoice',exact:true}).click();
  await expect(page.locator('#detail')).toBeVisible();
  await page.getByLabel('Payment amount (₹)').fill('100');
  await page.getByRole('button',{name:'Record payment',exact:true}).click();
  await expect(page.locator('#invoice-paper')).toContainText('490.00');
  await page.getByRole('button',{name:'OPD',exact:true}).click();await page.getByRole('button',{name:'OPD history',exact:true}).click();await page.getByLabel('Search OPD visits').fill('Browser Test Patient');
  await expect(page.locator('#opd-rows tr')).toHaveCount(2);
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'New OPD registration',exact:true}).click();
  await expect(page.locator('#opd-form')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('opd-mobile.png'),fullPage:true});
  await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.locator('#login')).toBeVisible();
  expect(errors).toEqual([]);
});
